services:
  nextjs-website:
    build:
      context: .
      args:
        - MONGODB_URI=${MONGODB_URI}
        - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    container_name: website-blog-milan-mareels
    restart: unless-stopped
    ports:
      - "3003:3000"
    depends_on:
      - mongodb-server

  mongodb-server:
    image: mongo:latest
    container_name: mongodb-blog-database
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
